# Uncomment this line to define a global platform for your project
platform :ios, '7.0'

source 'https://github.com/CocoaPods/Specs.git'

pod 'AWSCognito', '~> 2.1.0'
pod 'AWSiOSSDKv2'
pod 'RMMapper'
pod 'Facebook-iOS-SDK', '~> 4.0'
#pod 'MCSwipeTableViewCell', '~> 2.1'
pod 'MGSwipeTableCell', '~> 1.4'
pod 'NZCircularImageView', '~> 0.0'
pod 'NSDate+TimeAgo', '~> 1.0'
pod 'RMUniversalAlert', '~> 0.5'
pod 'QBImagePickerController', '~> 2.0'
pod 'ZLSwipeableView'
pod 'AFNetworking', '~> 2.0'
pod 'VGParallaxHeader'
pod 'SVProgressHUD'
pod 'TPKeyboardAvoiding', '~> 1.2'
#pod 'ECSlidingViewController', '~> 2.0.3'
pod 'MZFormSheetController', '~> 2.0'
pod 'RESideMenu', '~> 4.0.7'
pod 'UITextView+Placeholder'
pod 'KAProgressLabel'
pod 'SDWebImage', '~>3.7'
pod 'UIActivityIndicator-for-SDWebImage', '~> 1.2'
pod 'NSString+TextAndNumberValidation', '~> 0.11'
#pod 'XHImageViewer'
#pod 'NYTPhotoViewer'
#pod 'IDMPhotoBrowser', '~> 1.6'
#pod 'BSKeyboardControls', '~> 2.2'
#pod 'google-plus-ios-sdk'
pod 'EBPhotoPages', '~> 0.9.1'
#pod 'MGImageUtilities', '~> 0.0'
pod 'PixateFreestyle'
pod 'APAddressBook'